#ifndef GaMaLib___gama_ellipsoids__header_file_h
#define GaMaLib___gama_ellipsoids__header_file_h

#include <gamalib/ellipsoid.h>

// This file was generated by GNU GaMa (program ellipsoids_xml 0.01)
// from http://www.gnu.org/software/gama/xml/ellipsoids.xml

namespace GaMaLib {

enum gama_ellipsoid {

ellipsoid_unknown,
ellipsoid_airy,		// 6377563.541   6356257.053
ellipsoid_australian,		// 6378160   298.25
ellipsoid_bessel,		// 6377397.15508   6356078.96290
ellipsoid_clarke1858a,		// 6378361   6356685
ellipsoid_clarke1858b,		// 6378558   6355810
ellipsoid_clarke1866,		// 6378206.4   6356583.8
ellipsoid_clarke1880,		// 6378316   6356582
ellipsoid_clarke1880m,		// 6378249.145   293.465
ellipsoid_everest,		// 6377276.348   6356075.416
ellipsoid_fisher1960a,		// 6378166.0   298.3
ellipsoid_fisher1960b,		// 6278155.0   298.3
ellipsoid_grs80,		// 6378137   0.003352810681182
ellipsoid_helmert,		// 6378200   298.3
ellipsoid_international,		// 6378388   297
ellipsoid_krassovski,		// 6378245   298.3
ellipsoid_mercury,		// 6378166   298.3
ellipsoid_schott,		// 6378157   304.5
ellipsoid_sa1969,		// 6378160   298.25
ellipsoid_wgs84		// 6378137   0.003352810664747

};

extern const char * const gama_ellipsoid_caption[];

gama_ellipsoid ellipsoid(const char*);
int            set(Ellipsoid*, gama_ellipsoid);

}

#endif
