GNU Gama  can be found in the subdirectory @code{/gnu/gama/} on
your favourite @uref{http://www.gnu.org/prep/ftp.html, GNU mirror} or
checked-out from the GIT. See our project page at
@uref{http://savannah.gnu.org/projects/gama/, savannah} for more
information.

To get an anonymous read-only access to the GIT repository for the
latest GNU Gama source, issue the following command

@example
git clone git://git.sv.gnu.org:/sources/gama.git
@end example

@menu
* Examples::
@end menu

@node       Examples
@subsection Examples
@cindex     examples

The collection of sample networks is available as a separete CVS
module. To checkout the @code{gama-local} examples from CVS use the
command

@example
git clone git://git.sv.gnu.org:/gama/example.git
@end example

