The latest GNU Gama stable version can be found on in the subdirectory
@code{/gnu/gama/} on your favourite
@uref{http://www.gnu.org/prep/ftp.html, GNU mirror} or from the CVS as
the branch @code{@value{GAMA_DOC_STABLEV}}.  See our project page at
@uref{http://savannah.gnu.org/projects/gama/, savannah} for more
information.  

Development branch version @code{@value{GAMA_DOC_VERSION}} is available from
the CVS on the main trunk or from the alpha GNU FTP server
@uref{ftp://alpha.gnu.org/gnu/gama/}.  Archive of previous versions
(both stable and unstable) is available at
@uref{http://gama.fsv.cvut.cz/gama/archive/}.


To get an anonymous read-only access to the CVS repository for the
latest GNU Gama unstable source, submit the following commands

@example
cvs -d:pserver:anoncvs@@subversions.gnu.org:/cvsroot/gama login
cvs -z3 -d:pserver:anoncvs@@subversions.gnu.org:/cvsroot/gama co gama
@end example

@noindent or

@example
cvs -z3 -d:pserver:anoncvs@@subversions.gnu.org:/cvsroot/gama 
         co -r @value{GAMA_DOC_STABLEV} gama
@end example

@noindent for the stable branch @code{@value{GAMA_DOC_STABLEV}}.

To download from CVS only the matrix/vector C++ template library
@code{matvec} run
@example
@c cvs -d:pserver:anoncvs@@subversions.gnu.org:/cvsroot/gama login 
cvs -z3 -d:pserver:anoncvs@@subversions.gnu.org:/cvsroot/gama 
         co gama/matvec
@end example



@menu
* Examples::
@end menu

@node       Examples
@subsection Examples
@cindex     examples

The collection of sample networks is available as a separete CVS
module. To checkout the @code{gama-local} examples from CVS use the
command

@example
cvs -z3 -d:pserver:anoncvs@@subversions.gnu.org:/cvsroot/gama 
         co examples
@end example


