#!/bin/bash

GAMAL=../../bin/gama-local
GAMAT=../../bin/gama-local-xml2txt
TMP=results

rm -f $TMP/par.xml $TMP/nop.xml $TMP/par.tmp $TMP/nop.tmp

$GAMAL ./input/gama-local-par.gkf > $TMP/par.xml
$GAMAL ./input/gama-local-nop.gkf > $TMP/nop.xml \
    --algorithm gso \
    --cov-band  1 \
    --latitude  50.2 \
    --ellipsoid wgs84

diff -s $TMP/par.xml $TMP/nop.xml
if test -n "$(diff $TMP/par.xml $TMP/nop.xml)" ; then
    exit 1
fi

$GAMAT < $TMP/par.xml > $TMP/par.txt
$GAMAT < $TMP/nop.xml > $TMP/nop.txt

diff -s $TMP/par.txt $TMP/nop.txt
if test -n "$(diff $TMP/par.txt $TMP/nop.txt)" ; then
    exit 1
fi

if test "x$GNU_GAMA_LOCAL_TEST_XMLLINT" != "xyes"; then
    xmllint --schema ../../xml/gama-local.xsd --noout \
        ./input/gama-local-par.gkf
    xmllint --schema ../../xml/gama-local.xsd --noout \
        ./input/gama-local-nop.gkf
    xmllint --schema ../../xml/gama-local-adjustment.xsd --noout $TMP/par.xml
    xmllint --schema ../../xml/gama-local-adjustment.xsd --noout $TMP/nop.xml
fi

rm -f $TMP/par.xml $TMP/nop.xml $TMP/par.tmp $TMP/nop.tmp
