#!/bin/sh
#
# GNU GaMa script get-gamalib-version
# ===================================
# 
# This script must be run in the parent directory of subdirectories
# gamalib, gamaprog and scripts. If we are in subdirectory ./scripts,
# we go one level up.
#
# $Id: get-gamalib-version,v 1.2 2002/09/21 10:15:33 cepek Exp $

if pwd | grep scripts$; then cd ..; fi


awk '/GaMaLib_version/ {print $5 ; exit }' gamalib/version.cpp \
    | tr --delete /\"\;/
