#!/bin/sh
#
# GNU Gama script get-gamalib-version
# ===================================
# 
# This script must be run in the parent directory of subdirectories
# gamalib, gamaprog and scripts. If we are in subdirectory ./scripts,
# we go one level up.
#
# $Id: get-gamalib-version,v 1.3 2003/03/29 13:33:57 cepek Exp $

if pwd | grep scripts$; then cd ..; fi


awk '/GNU_gama_version/ {print $5 ; exit }' gnu_gama/version.cpp \
    | tr --delete /\"\;/
