#! /bin/bash

# aktualizace nove verze GaMa na serveru gama.fsv.cvut.cz
# ----------------------------------------------------------------------
# ~/gama/update-GaMa                                                (AC)
#
# $Id: upgrade-GaMa,v 1.1 2001/12/07 11:45:44 cepek Exp $

# Skript se spousti z adresare ve kterem jsou podadresare gamalib,
# gamaprog a scripts.  Pokud jsem v podadresari ./scripts, prejdu o
# jednu uroven vys.

if pwd | grep /scripts$; then cd ..; fi

# nejprve prevedu vsechny archivni soubory z bz2 do tgz (pokud existuji)

for i in `ls | grep ^gamalib- | grep tar.bz2$` 
do                                              
   echo $i --\> tgz 
   GaMaVer=`echo $i | sed s/.tar.bz2//` 
   bunzip2 $GaMaVer.tar.bz2 
   gzip    $GaMaVer.tar     
   mv      $GaMaVer.tar.gz $GaMaVer.tgz 
done


# zjistim nejnovejsi verzi gamalib

for i in `ls | grep ^gamalib- | grep \.tgz$` 
do                                
   VERSION=`echo $i | sed s/.tgz//`
   GaMaVer=$VERSION.tgz
done

rm -f   $VERSION 2>/dev/null
if [ -d $VERSION ]; then
   echo
   echo $VERSION directory exists - upgrade failed!
   echo
   echo
   exit 1
fi
ln -s . $VERSION


if [ "$GaMaVer" = "" ]; then
   echo
   echo nenalezen zadny archivni soubor gamalib-...
   echo
   exit 1
fi
if [ ! -d expat ]; then
   echo
   echo nenalezen adresar ./expat - upgrade neproveden
   echo
   exit 1
fi


# vycistim vse co zde mohlo zbyt, rozbalim a prelozim ...

rm -rf gamalib gamaxml gmatvec scripts gamaprog *.md5sum *~
tar xvzf $GaMaVer
scripts/Build_GaMa

# nakopiruji vse, co je treba

echo
echo nejnovejsi verze je $GaMaVer
echo

DIRVER=$(echo $GaMaVer | sed s/gamalib-// | awk -F. '// { print $1"."$2 }')
Archiv=./archive/gamalib/$DIRVER

if [ -d $Archiv ]; then
   if ! [ -f $Archiv/$GaMaVer ]; then
      chmod a+r $GaMaVer
      cp $GaMaVer $Archiv
      echo cp $GaMaVer $Archiv
   else
      echo ponechan existujici soubor $Archiv/$DIRVER/$GaMaVer
   fi
else
   echo neexistuje adresar $Archiv
fi

GaMaEmail=/var/www-user/cepek/MailServer/gama-email

if [ -d $GaMaEmail ]; then
   rm -f    $GaMaEmail/gama
   cp       ./gamaprog/linux/gama/gama $GaMaEmail
   echo cp  ./gamaprog/linux/gama/gama $GaMaEmail
else
   echo neexistuje adresar $GaMaEmail
fi

rm  $VERSION
echo

# --------------------------------------------------------------------












