#! /bin/bash

# aktualizace nove verze gmatvec-demo na serveru gama.fsv.cvut.cz  
# ----------------------------------------------------------------------
# ~/gama/update-gmatvec-demo                                        (AC)
#
# $Id: upgrade-gmatvec-demo,v 1.1 2001/12/07 11:45:44 cepek Exp $

if ! [ -d archive/gmatvec ]; then
   echo
   echo neexistuje adresar archive/gmatvec
   echo
   exit 1
fi

echo
for i in `ls | grep ^gmatvec-demo- | grep tgz$` 
do
   if ! [ -f archive/gmatvec/$i ]; then
      cp $i archive/gmatvec
      echo cp $i archive/gmatvec
   fi
done
echo

# --------------------------------------------------------------------
