#! /bin/bash

# aktualizace nove verze dokumentace gmatvec na serveru gama.fsv.cvut.cz  
# ----------------------------------------------------------------------
# ~/gama/update-gmatvec-doc                                         (AC)
#
# $Id: upgrade-gmatvec-doc,v 1.1 2001/12/07 11:45:44 cepek Exp $

# vsechny gmatvec-doc*.bz2 podle potreby prekopiruji do gmatvec-doc

if ! [ -d gmatvec-doc ]; then
   mkdir gmatvec-doc
fi

for i in `ls | grep ^gmatvec-doc- | grep tar.bz2$` 
do                                       
   gMatVecVersion=$i  

   if ! [ -f gmatvec-doc/$gMatVecVersion ]; then
      cp $gMatVecVersion gmatvec-doc
      echo  cp $gMatVecVersion gmatvec-doc/
   fi
done


if [ -d archive/gmatvec ]; then
   if ! [ -f archive/gmatvec/$gMatVecVersion  ]; then
      cp $gMatVecVersion archive/gmatvec
   fi
fi 

cd gmatvec-doc

if ! [ -f Makefile ]; then
    tar xIf $gMatVecVersion
fi

make update-new-version

# --------------------------------------------------------------------
